### ISSUE TITLE
Get initial list of repositories to harvest from

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/research-data-harvester#2]

**Comment by windcowles** [comment]
Zenodo (zenodo.org) - A widely respected/used, domain-general repository
Here is a dataset from a Princeton researcher: https://zenodo.org/record/3759736#.Xr2UWhPYrfY

**Comment by windcowles** [comment]
Dryad (datadryad.org) - A domain-general repository that publishers are increasingly encouraging authors to use
Here is a link to their architecture: https://datadryad.org/stash/our_platform
Here is a dataset from a Princeton researcher: https://datadryad.org/stash/dataset/doi:10.5061/dryad.h5r7m66

**Comment by windcowles** [comment]
OpenNeuro (openeuro.org) - A domain-specific repository that I know several of our neuroscience researchers use
Here are a couple datasets from Princeton researchers: 
https://openneuro.org/datasets/ds001131/versions/1.0.0
https://openneuro.org/datasets/ds002345/versions/1.0.1

**Comment by windcowles** [comment]
NIMH Data Archive (nda.nih.gov) - One of several required repositories that NIH hosts for data generated from NIH-funded projects. This is one that I know has a least some Princeton-generated data. This is a different kind of repo because it includes additional information re: funding and other relevant project data. If it's too much of an odd duck, we could leave it until another round.
Here is a dataset from a Princeton researcher: https://nda.nih.gov/edit_collection.html?id=2521

**Comment by windcowles** [comment]
DataVerse (dataverse.harvard.edu) -- A Harvard developed domain-general repository that is distributed, with Harvard as the central hub. Many Princeton researchers use this one.

Here are a couple datasets from Princeton researchers:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/1FUZ0S
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HTMX3K

**Comment by hackartisan** [comment]
Thank you!
